"""empty message

Revision ID: a86ee47a2960
Revises: f58169f61d4d
Create Date: 2026-03-11 17:16:34.021212

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a86ee47a2960"
down_revision = "f58169f61d4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("media_type", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("thumbnail_path", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("duration", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_column("duration")
        batch_op.drop_column("thumbnail_path")
        batch_op.drop_column("media_type")

    # ### end Alembic commands ###
