"""Add user authentication with sessions and google

Revision ID: f58169f61d4d
Revises: 285667a81ad7
Create Date: 2025-03-26 16:47:02.570662

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f58169f61d4d"
down_revision = "285667a81ad7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_hash", sa.String(length=256), nullable=True)
        )
        batch_op.add_column(
            sa.Column("google_id", sa.String(length=256), nullable=True)
        )
        batch_op.create_unique_constraint(None, ["google_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("google_id")
        batch_op.drop_column("password_hash")

    # ### end Alembic commands ###
